# Generated by Django 4.0.4 on 2022-09-10 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning_logs', '0004_uploadimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploadimage',
            name='title',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
