# Generated by Django 4.0.4 on 2022-09-10 14:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('learning_logs', '0006_entry_image_entry_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='uploadimage',
            name='entry',
        ),
    ]
