# Generated by Django 4.0.4 on 2022-09-10 14:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('learning_logs', '0007_remove_uploadimage_entry'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UploadImage',
        ),
    ]
