# Generated by Django 4.0.4 on 2022-09-14 05:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('learning_logs', '0010_entry_image'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UploadImage',
        ),
    ]
