# Generated by Django 4.0.4 on 2022-10-21 05:42

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('learning_logs', '0012_entry_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='entry',
            name='eligibility',
            field=models.CharField(default=django.utils.timezone.now, max_length=200),
            preserve_default=False,
        ),
    ]
