# Generated by Django 4.0.4 on 2022-11-28 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning_logs', '0014_entry_entry_owner'),
    ]

    operations = [
        migrations.CreateModel(
            name='Apply',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entry_id', models.CharField(max_length=20)),
                ('owner_id', models.CharField(max_length=20)),
                ('applicant_id', models.CharField(max_length=20)),
            ],
        ),
    ]
