# Generated by Django 4.0.4 on 2022-12-21 13:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('learning_logs', '0017_profile_postal_code_alter_profile_address_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apply',
            name='applicant_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='apply',
            name='entry_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='learning_logs.entry'),
        ),
        migrations.AlterField(
            model_name='apply',
            name='owner_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='owner', to=settings.AUTH_USER_MODEL),
        ),
    ]
