# Generated by Django 4.0.4 on 2022-12-21 13:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('learning_logs', '0018_alter_apply_applicant_id_alter_apply_entry_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apply',
            name='applicant_id',
            field=models.ForeignKey(db_column='applicant_id', on_delete=django.db.models.deletion.CASCADE, related_name='user', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='apply',
            name='entry_id',
            field=models.ForeignKey(db_column='entry_id', on_delete=django.db.models.deletion.CASCADE, to='learning_logs.entry'),
        ),
        migrations.AlterField(
            model_name='apply',
            name='owner_id',
            field=models.ForeignKey(db_column='owner_id', on_delete=django.db.models.deletion.CASCADE, related_name='owner', to=settings.AUTH_USER_MODEL),
        ),
    ]
