# Generated by Django 4.0.4 on 2022-12-28 12:59

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('learning_logs', '0019_alter_apply_applicant_id_alter_apply_entry_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='email',
            field=models.EmailField(default=django.utils.timezone.now, max_length=254),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='profile',
            name='family_name',
            field=models.CharField(default=django.utils.timezone.now, max_length=10, verbose_name='苗字'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='profile',
            name='first_name',
            field=models.CharField(default=django.utils.timezone.now, max_length=10, verbose_name='名前'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='profile',
            name='sex',
            field=models.CharField(choices=[('男', '男'), ('女', '女'), ('選択しない', '選択しない')], default=django.utils.timezone.now, max_length=5, verbose_name='性別'),
            preserve_default=False,
        ),
    ]
