# Generated by Django 4.0.4 on 2022-12-28 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning_logs', '0020_profile_email_profile_family_name_profile_first_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='birthday',
            field=models.DateField(auto_now=True, verbose_name='生年月日'),
        ),
    ]
