# Generated by Django 4.0.4 on 2022-12-29 02:42

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('learning_logs', '0022_alter_profile_birthday'),
    ]

    operations = [
        migrations.AddField(
            model_name='apply',
            name='date_added',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
