# Generated by Django 4.0.4 on 2023-01-04 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning_logs', '0023_apply_date_added'),
    ]

    operations = [
        migrations.AddField(
            model_name='entry',
            name='address',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='entry',
            name='selection_method',
            field=models.TextField(default=2),
            preserve_default=False,
        ),
    ]
