# Generated by Django 4.0.4 on 2023-01-08 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning_logs', '0025_apply_prtext_apply_resume'),
    ]

    operations = [
        migrations.AlterField(
            model_name='topic',
            name='text',
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
