# Generated by Django 4.0.4 on 2023-01-09 09:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('learning_logs', '0027_recommend'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recommend',
            name='owner',
        ),
    ]
